### ISSUE TITLE
Document use cases for passing of data in files to functions

### ISSUE THREAD

**Issue by kemartin2015** [RockefellerArchiveCenter/rac_aspace#30]
**Is your feature request related to a problem? Please describe.**
As it stands now, the README does not include serialized data in the 'Enable User Input' section. This was a functionality used in many scripts from other institutions. Ex. [Batch Update Top Containers](https://github.com/ruthtillman/ASpaceASnake#batch-update-top-containers---batch-update-top-containerspy)

**Describe the solution you'd like**
Add a bullet point in the 'Enable User Input section' to indicate batch upload and batch update of serialized data.

**Comment by helrond** [comment]
Good catch! I've renamed the issue to make it a little more apparent what we're talking about here. I'm also wondering if this is more of a **configuration** issue as opposed to a **user input** issue?

**Comment by bonniegee** [comment]
The work required on this issue is to continue to scope out what this issue means (and add additional issues if necessary).

**Comment by helrond** [comment]
see #41
