### ISSUE TITLE
Document use cases for cleaning data in ArchivesSpace

### ISSUE THREAD

**Issue by daremiyo** [RockefellerArchiveCenter/rac_aspace#31]
**Is your feature request related to a problem? Please describe.**
May be useful to include a section in the README that describes sanitize data functionality. This functionality targets and cleans up problematic text in data fields that impedes use of data and may cause archival objects not to publish For example, HTML characters. 

**Describe the solution you'd like**
Add a new Sanitize Data section to the README.

**Describe alternatives you've considered**
This functionality may fit under the Data Helpers section of the README.

**Comment by helrond** [comment]
This is a good idea! I wonder if we can scope it a bit more tightly (and perhaps rename so we're not unwittingly reinforcing oppressive language). If this is _really_ just about removing HTML characters, let's just have a function called `strip_html()` or something. If we want to do other things, then let's specify what those are and perhaps have a function for each of them?

**Comment by bonniegee** [comment]
The work required on this issue is to split it out into additional issues. When this is finished, this issue can be closed.

**Comment by helrond** [comment]
See:
- #42 - HTML strip
- #43 - remove trailing characters
- #44 - escape HTML
