### ISSUE TITLE
Add function to open data files and return an iterable

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/rac_aspace#41]
**Is your feature request related to a problem? Please describe.**
To address #30 @daremiyo and I think it would be good to have a function that can turn a file into something that a script can use natively.

**Describe the solution you'd like**
Create a function that takes a filepath for an input file (in CSV or Excel) and returns an iterable that can be used in a script.

**Comment by bonniegee** [comment]
Would this be in `data_helpers.py`, or is that open for discussion?

**Comment by helrond** [comment]
I think it's open for discussion but I'd suggest putting it in `data_helpers.py` for now.
