### ISSUE TITLE
Research how ASnake handles configs and propose a standard approach we can use

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/rac_aspace#51]
**Is your feature request related to a problem? Please describe.**
ArchivesSnake takes a particular approach to finding configs (I think). This will impact how we do configuration going forward.

**Describe the solution you'd like**
Research how ASnake handles configs and propose a standardized approach we can use going forward.

**Comment by kemartin2015** [comment]
- The most basic ASnake config file is a .archivessnake.yml file with `baseurl` for the ArchivesSpace backend API, then `username` and `password` for access to that API. 
```
baseurl: http://localhost:8089
username: 
password: 
```
- Asnake looks for the yml file in the home directory:
      - For OS X and Linux -  /home/[my user name]/.archivessnake.yml
      - For Windows - C:\Users\[my user name]\.archivessnake.yml

- The ArchivesSnake README includes a table with more [advanced configuration features.
](https://github.com/archivesspace-labs/ArchivesSnake#configuration), including logging. Here's a good description of the Python default [5 levels of logging](https://www.machinelearningplus.com/python/python-logging-guide/). From what I've read, INFO seems like a good level to keep.

- `retry_with_auth` is an optional addition. The default value is TRUE to try to reauthorize authentication when encountering a 403: forbidden error 

- Overall, I think we will need a standard config file that authenticates ArchivesSpace, provides a destination for serialization, and sets logging standards. 

This is a more condensed version of the local_settings.cfg we use now.

```
[ArchivesSpace]
baseURL:
repository:
username
password:

[Destinations]
directory: 
filename: .csv

[Logging]
filename:.txt
level: INFO
```
