### ISSUE TITLE
Add unit tests for data helpers that require data from ArchivesSpace

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/rac_aspace#61]
**Is your feature request related to a problem? Please describe.**
In order to know that our code is working (and remains working as we update it) we should have unit tests in place which assert expected outputs given prescribed inputs. This requires additional setup work than unit tests which do not require data from ArchivesSpace, so this issue has been scoped separately.

**Describe the solution you'd like**
Unit tests for all of the functions in `data_helpers.py` that require data from ArchivesSpace

**Comment by helrond** [comment]
fixed by a1f7a0e2fd3e473eb5c57b62b48c20d9c0791854
