### ISSUE TITLE
Add query string parameters to `indicates_restriction()` and `is_restricted()` methods

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/rac_aspace#84]
**Is your feature request related to a problem? Please describe.**
Currently `is_restricted` hardcodes a query string to look for in notes as a flag for whether or not an object is restricted. Similarly, `indicates_restriction` looks at hardcoded acts to determine whether or not a rights statement indicates a restriction. 

**Describe the solution you'd like**
To accommodate the broadest possible use cases, and to make this logic as visible as possible, both of these functions should be refactored to include a parameter that can be passed for these values.

**Comment by p-galligan** [comment]
What variable are we trying to replace with a query string in `indicates_restriction`? The restrictions list? I thought those were pretty set values generated by AS that wouldn't change.

**Comment by helrond** [comment]
@p-galligan `indicates_restriction` should take a list of act restrictions (for example, ["disallow", "conditional"]) which indicate that there's a restriction. Some orgs might not consider "conditional" a restriction, others might.

You're right that these values are controlled, however they are controlled by an enum list that's available for editing in the UI, which means that someone could add or subtract to that list.
