### ISSUE TITLE
Change docstring style from Google to Sphinx

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/rac_aspace#90]
**Is your feature request related to a problem? Please describe.**
The documentation for this project uses Google style docstrings. The ArchivesSnake library uses Sphinx style docstrings to generate documentation. In order to contribute the code from this project to the ArchivesSnake library, the docstrings should be updated.

**Describe the solution you'd like**
Docstrings should be changed to match Sphinx syntax.

**Comment by HaSistrunk** [comment]
I'm thinking this means we need to convert to them to the reStructuredText format, but we can double check to see what the ArchivesSnake library is doing. 

Right now we are using an extension in our autodoc config called Napolean`(sphinx.ext.napoleon` ) that is a preprocessor that converts our Google-style docstrings to reStructuredText before autodoc processes them. If we convert to reStructuredText, we can remove that.
